### ISSUE TITLE
Statistics panel gone

### ISSUE THREAD

**Issue by Klievan** [Belieal/flipping-utilities#104]
Whenever I click on the statistics tab, the whole client freezes for up to 3 seconds after which it displays an almost empty panel:
![image](https://user-images.githubusercontent.com/5279685/92624142-7430f280-f2c7-11ea-87d4-d68bedf22747.png)

Running on the latest version of RuneLite. I have tried resetting the statistics without any success.

**Comment by zumaad** [comment]
Hi, thanks for the issue description and picture! 

Could you contact me on discord at gaymersriseup#4026 so that you can share the client logs and we can take a look at some other info?

**Comment by zumaad** [comment]
resolved after some teamwork and great debugging by @Klievan :)

for posterity:

problem was with not setting the madeBy field of an offer event correctly. This then caused the madeBy field to be null and when it was persisted, the offer event was persisted without a madeBy field. Thus, on startup serialization the madeBy field was set to null as it was missing from the trades json file. Since it was missing it also meant there was no "null" in the trades json file which made it more confusing when debugging.
