### ISSUE TITLE
Incorrectly Tracking Prices

### ISSUE THREAD

**Issue by Spuddya7x** [Belieal/flipping-utilities#121]
Ive merched a couple Scythe of Vitur's, and the prices werent tracked properly. It has the trade values backwards, and thinks ive made 11M loss on each of them. Is there a way to delete trades individually?
![Screenshot_9](https://user-images.githubusercontent.com/48963293/99187422-70e63700-274e-11eb-9830-e66f316b9858.png)

**Comment by zumaad** [comment]
hmm that is odd. That can occur when there are unaccounted for trades because you flipped on mobile and so the buys/sells get mismatched. 

The only way to delete trades semi-individually currently is to select the appropriate time interval in the stats tab and delete the item. That will delete all the trades for that item in that time interval, but of course you risk losing correctly tracked trades in that time interval too. 

I think in a future update I can add the ability to delete individual buys and sells. As a side note, in the buys/sells tab does it show the correct buys and sells for the Scythe of Vitur?

**Comment by Spuddya7x** [comment]
Okay, I think ive just found the cause of these problems, and how to replicate.
1, Buy an item on Day 1, for X price.
2, Sell the Item on Day 2, for Y price.
3, Buy the same item again, on Day 2, for Z price.
The "All" Timeframe tracks correctly for Step 1 and 2, but the "Session" time frame, only tracks step 2. 
So when you do step 3, if Z price is higher, it thinks you sold for Y on the day, and bought for Z on the day, making a loss.

This Image below was a step 2 sale, from an earlier purchase;
![image](https://user-images.githubusercontent.com/48963293/100026193-3a5d8b80-2de2-11eb-9122-9748e9d86157.png)

This image however, was after an instabuy, after I had sold the rapier beforehand. The price had gone down, so it thinks I profited by "Replacing" my rapier which was sold.
![image](https://user-images.githubusercontent.com/48963293/100026214-48131100-2de2-11eb-810e-4ba741ed602a.png)

I hope this helps, and is of use to you. :D

**Comment by zumaad** [comment]
ahhhh, excellent description! yeah that makes sense. Thats the intended behavior, as the plugin can't know that the "sell for y price on day 2" was part of the "flip" from day one. It only knows it came in on day 2 and so it matches it with the other offer from day 2 in the session interval.

There isn't really a way to mitigate such occurrences. One thing that might come to mind is to not combine offers into "flips" if the sell comes before the buy, but there are edge cases where that causes flips to not be constructed properly. 

I wonder if I can add some sort of info to the flip visual that shows when a "flip" could potentially be wonky due to such edge cases.

**Comment by Spuddya7x** [comment]
Yeah, perhaps something that asks a question "Does this look correct?"
