### ISSUE TITLE
Support for deleting an item (panel) from the window

### ISSUE THREAD

**Issue by zumaad** [Belieal/flipping-utilities#2]
First of all, this is an awesome plugin, thanks for creating it!

The ability to delete specific items off the main window would be great. Currently, there is a refresh button which deletes everything, but sometimes you only want to delete certain items (there is a minimize option but it still leaves things cluttered). A little button or something to click on to dismiss/delete an item panel would be really useful. Alternatively, having the minimize button push the minimized item to the bottom thus essentially removing it from your view would also work.

**Comment by Belieal** [comment]
Hi Zumaad and thank you for the kind words! 😃 

I love your suggestion and I don't think it would be too difficult to add a small icon to each item's panel in order to delete it. I agree with you that the minimize feature is a bit arbitrary at times (especially because it just reopens after every update...), so I've been thinking of replacing that whole feature with just the delete button. I may revisit it at a later date to fix the issues it has.

I will be implementing your suggestion in the next version alongside potentially a search bar and another feature I've just discovered could be possible! 😅

**Comment by zumaad** [comment]
Sweet, sounds awesome!
