### ISSUE TITLE
Buy price / Sell price swapping sometimes.

### ISSUE THREAD

**Issue by kevindv001** [Belieal/flipping-utilities#21]
hi.

Been using this plugin for a week now and i love it.
But since today I sometimes have the problem that my buy/sell price swap.
So i don't know the original buy price anymore and need to look in my history.

For example : https://i.imgur.com/ApWyqaJ.png

Here i made a new offer with a little undercut. but somehow it replaced my buy offer (even tho it was a sell, and i can't see the original buy price anymore)

Example : https://i.imgur.com/4rBC4jc.png

Hope this can be fixed :)

**Comment by Belieal** [comment]
Hi there and I'm glad you like the plugin! :)

Your issue is due to how the plugin detects and registers margin checks. Any item that is trades with a total quantity of one is recognized as a margin check and the price will therefore be updated accordingly. This has the side effect that when you flip individual items, the plugin will think it's a margin check and update thus swapping the price.

To alleviate this for now, you can right-click the item name to the "freeze" the margin checker, meaning that the item won't have its price updated until you "unfreeze" it again.

**Comment by kevindv001** [comment]
Thanks you !

Didn't know about the freeze option.
Gonna make sure to freeze when doing individual items !
