### ISSUE TITLE
Profit???

### ISSUE THREAD

**Issue by Eliofx92** [Belieal/flipping-utilities#36]
The potential profit showed after margin check but after I purchased them it disappears.

can you always keep profit there please? its useful information whilst selling too

<img width="1561" alt="Screenshot 2020-04-15 at 19 56 42" src="https://user-images.githubusercontent.com/63731741/79377594-d9203080-7f53-11ea-9137-1ea7312b8cb6.png">

**Comment by telans** [comment]
I assume this is because as the GE Limit has gone to zero, so does the potential profit.

The plugin has a statistics tab showing the profit/loss history of items but it's not currently updated within RuneLite

**Comment by zumaad** [comment]
The reason this is happening because the buy price is listed as 375999 and the sell price is also listed at 375999, so the plugin thinks the profit for each item is 0 (as the buy and sell price is the same). I assume what happened is that you margin checked the seer's rings and then sold/bought a quantity of 1 after that and because the margin wasn't frozen and it was a sold/bought offer with a quantity of 1, the plugin couldn't differentiate that offer from a margin check and as such, it updated the display with that price. 

To solve this, you should freeze the margin, by right clicking the name of the item. This is so that future buy/sells with a quantity of 1 don't update the margin display

**Comment by Eliofx92** [comment]
can't you automate the freezing and detect the margin check? most people buy something for 10x the price then sell for 1gp. can't you detect the 1gp sell to update the margin?

**Comment by Belieal** [comment]
No, that would not work. We are looking into different ways of determining margin checks, but for now freezing the margin is the best we can do. I suggest you look into the config and check "Automatically freeze the margin for new items" if you would like to automatically freeze newly checked items.

**Comment by zumaad** [comment]
Well, that's not how I margin check, especially with more expensive items. Its risky to put a buy offer for really high to get an insta buy as maybe there are few sellers on the market and the best sell offer is set for a really high price. I have personally been burned by this several times :(, so I stopped putting offers in for high.

The crux of the problem is that there is no consistent way to differentiate a margin check offer from a regular offer with a quantity of 1. So, we have to assume every offer with a quantity of 1 is a margin check and leave it up to the user to freeze the margin.

Attempts to automate this would rely on guesswork that applies to some people and not to others and would lead to lots of confusion.

**Comment by zumaad** [comment]
> can't you automate the freezing and detect the margin check? most people buy something for 10x the price then sell for 1gp. can't you detect the 1gp sell to update the margin?

Well, that's not how I margin check, especially with more expensive items. Its risky to put a buy offer for really high to get an insta buy as maybe there are few sellers on the market and the best sell offer is set for a really high price. I have personally been burned by this several times :(, so I stopped putting offers in for high.

The crux of the problem is that there is no consistent way to differentiate a margin check offer from a regular offer with a quantity of 1. So, we have to assume every offer with a quantity of 1 is a margin check and leave it up to the user to freeze the margin.

Attempts to automate this would rely on guesswork that applies to some people and not to others and would lead to lots of confusion.
