### ISSUE TITLE
Aborting offer bug

### ISSUE THREAD

**Issue by Baklap4** [Belieal/flipping-utilities#48]
First of all; Great plugin love it!
However i found a little annoying bug;
When having a current offer in, then halfway aborting it it won't extract the bought items from the buy limit. it'd be nice to have to bug fixed

**Comment by Belieal** [comment]
Hi there and thank you for the bug report. I'm glad you like the plugin! :)

Fortunately, this is a known bug that has already been fixed. It'll be included in the next update! :)

**Comment by Baklap4** [comment]
Aight awesome! Can you reference the pull request + original issue? Then i'll close the issue :)

**Comment by Belieal** [comment]
I don't think we had an issue or PR open for this bug, as it was pretty simple ([Here's the commit for it](https://github.com/Belieal/flipping-utilities/commit/9f47b6b6663c09eac0133a8b25e7124fd78f5321#diff-209c1369f1d3d917d45671e0be4f37feR311)). Although, please keep this issue open since this bug has been reported a few times before as well.

I'll close this once the update is released on the plugin hub! :)

**Comment by Baklap4** [comment]
Ahh thanks for the reference :) Any idea on when 1.3 is going to get out or any way we can help testing it?

**Comment by Belieal** [comment]
You can follow development on v1.3 with PRs #41 and #35. When #35 is merged I'll send it for review with RuneLite and should be released shortly after. I don't currently have a specific date, but I think we could feasibly release before next sunday, bar any nasty bugs.

If you know how to build with IntelliJ/gradle, I'd be really appreciative if you'd test out my beta branch (stat-tab-pr) and report any bugs/suggestions you might have! :)
