### ISSUE TITLE
when?!?

### ISSUE THREAD

**Issue by juglia02** [Belieal/flipping-utilities#59]
This plugin is amazing!!! when will you be adding Favorited items and Grouped checklist tab with import and export features so you can keep track of the items you like to flip most!

Such important features and you are such a talented coder so will be super easy for you

please add this

**Comment by Belieal** [comment]
I'm glad you like the plugin. :) Unfortunately, this likely won't be a feature until at least v1.5 as we're dedicating v1.4 towards adding and expanding widgets.

**Comment by juglia02** [comment]
That is a shame but I trust your judgement. Can you tell us about what widgets you are adding and expanding?

**Comment by Belieal** [comment]
Well, currently we're looking at:

- Adding a timer for how long ago the last item was bought or sold in a trade, so you can determine if an item is buying or selling too slowly such that you can adjust the price. See #24.

- Expanding the price and quantity-setter widget (the one with the red text that you can click on when you're setting the price or quantity of an item) with incrementor and decrementor buttons.

- Using client scripts, possibly changing the way the buttons on the GE interface work:
  - Adding the ability to shift-click the +/- 5% price buttons to instead change the price by some other percentage.
   - Adding the ability to shift-click the quantity set up button to purchase the maximum amount you can buy with the coins in your inventory or the remaining GE limit - whichever is highest.

I'm still a bit unsure about if we're even allowed to run the client scripts, so that's a bit up in the air still. We may also add additional features if we get any good ideas while coding it. :)

**Comment by juglia02** [comment]
Adam allowed a bank pin script that lets you use the keyboard to type in so I am sure you are fine :)
