### ISSUE TITLE
Tackling profit tracker functionality- an outline

### ISSUE THREAD

**Issue by zumaad** [Belieal/flipping-utilities#6]
I anticipate this is going be a pretty big change and I didn't want to just go ahead and start working on it if you already were/wanted to, so I wrote up an outline and perhaps we can work on different parts/change it etc.

### **The outline**

**purpose:** To show a user's profits within a certain time window (past 4 hours, etc).

**my general high level idea:**

**Gui Changes:**

1. At the top of the flipping panel, show the the total profit calculation for an adjustable window of time (there can be some dropdown or just some int input that can be interpreted as hours)

2. There can be an entirely separate panel that you arrive at when you click a button. This panel will similarly show you total profit for an adjustable window of time, however since its a different panel, there can be more info added - such as breakdown of profit for every item you did in that window of time, rather than just a profit number.

3. The third idea is a combination of the two. The top of the flipping panel can show the total profit calculation and to get a more thorough breakdown of profit, you can click on the button that takes you to the profits panel. This is the option I prefer :)

**Calculating the profit**:

When calculating the profit, I assume that we always have some window of time that the user wants to see their profit for. For example, the user may want to see his profit for the last 4 hours (perhaps this can be the default is the user doesn't enter anything).

We have all the trades stored in each flipping item, so to calculate the profit for an item we can look at the arraylist of trades (the ones in each flippingitem), filter out the ones that are older than 4 hours (assuming the user wants to only see profit for the last 4 hours), and then add up the buy values and sell values (sell values will be positive, and buy can be negative). The resulting number will be the profit for that item within the last 4 hours. You can perform this operation on all the flipping items and sum the profits and that will be your profit for that window.

**Some caveats with the approach above**:  what happens if the number of X item (lets say the item is a lobster) that the user bought and sold is not the same (in the last 4 hours). For example, in the last 4 hours, they bought 4 lobsters and sold only 3. The algorithm above would show them at a loss as there are four buys and only 3 sells. So to handle this, and the other case where there are more sells than buys, we can find the number of sells and buys and only sum them up until the lowest one is exhausted. 

So, for example. In this case lets say the arraylist of trades looks like this (creating my own just for example): 
[("lobster", "buy",  -115gp, 1), ("lobster", "buy",  -115gp, 2), ("lobster", "buy",  -115gp, 1), ("lobster", "sell", 116gp, 2),  ("lobster", "sell", 116gp, 1)]

You could calculate the number of buys and sells. In this case, buys = 4, sells = 3. Keep track of the smaller number, this is the number of buys(3) you want to find and add to the number of sells(3), in this array. So lets say you now keep track of three variables, buys_to_look_for = 3, sells_to_look_for = 3, profit = 0. Then, you can iterate through the array, when you see a buy, you look at the quantity and subtract it from buys_to_look for and change the profit variable appropriately. If the quantity of the trade is greater than buys_to look_for, you can simply take the quantity you need, and change the quantity in the trade after subtracting what you took. You do this same process when you see sells except you subtract from sells_to_look_for. When both buys_to_look_for and sells_to_look_for are zero, you can stop iterating and return the profit!

With this solution to the uneven-buys-and-sells-problem, we won't get weird profit results. Also, typically you want to check your profit after a flipping session, when you have sold off everything. As such, in most relevant cases, buys and sells will be even anyway. So this is just to enable you to check your profit in the middle of a session without weird profit readings.

Sidenote: the widget you just recently added is really cool 👍

**Comment by Belieal** [comment]
Thank you so much for this write-up! You've certainly put a lot of effort into this. :)

## The GUI
I've always wanted this plugin to be an extension of the GE plugin as a whole. When I first started making it, I wanted it to have its own separate tab inside the GE panel though I quickly found out that this wasn't possible due to the permission limits of external plugins. So I made it its own panel instead while still being heavily influenced by the GE plugin in its design. I absolutely love the tab design it incorporates with the minimization of what is irrelevant to the user when using the plugin. I believe good design is a balance between not flooding the user with too much useless information while still not hiding on-demand features behind needlessly complicated menus. I think the GE plugin's way of handling this is great and I want this plugin to emulate that.

So in essence, I think that recreating the material tab layout of the GE plugin is the way to go with a ``Flipping Tab`` and a ``Statistics Tab``. 

Inside this statistics tab I think it should display the profits made with buttons to allow changes to the time interval of the profit calculation and profit/hour. Then, below the previous, I think it would be awesome to see records of individual flips. I envision this to have almost, if not the same, layout of the flipping panel that we have now. This would display the quantity flipped, profit per item, total profit, time it took to flip the items and profit/hour.

This is obviously a lot of work with a lot of new systems that needs to be implemented and it might be split up in individual update releases.

## The Calculation
The algorithm you describe sounds brilliant. I think it is really important for the user to be able to see what their profits are in real time. However it reminds me of another issue we may come across when developing this feature.

When I made the GE limit tracking I originally wanted it to show in real time, ie. whenever new items came through in a buy offer, I wanted it to change the GE limit as the items were being bought. Now the issue that I came across was that a ``SELLING`` or ``BUYING`` offerEvent will not show the amount of new items have been bought or sold. It will only record the amount bought so far. There was obviously an easy workaround with the GE limit since we don't really need the most up-to-date information so I would rather just count the amount bought on cancelled or finished offers and update the limit accordingly. But if we want the user to be able to track their profits in real time, we will need to figure out a way to determine and categorize the amount bought and sold inside an unfinished offer.

What ultimately may end up being the way to do this would be to create a class that stores the offer slot id and offer details with methods to add and extract the difference in quantities when new bought/sold items come in. This would be in the same vein as with how the GE plugin stores offers in ``SavedOffer``.


Please let me know what you think! :)

**Comment by zumaad** [comment]
Im on the same page when it comes to the GUI, I think thats a nice layout. Your solution for resolving the quantity bought/sold problem sounds great. I was thinking perhaps instead of the tradeHistory of each flippingitem just being an arraylist of GrandExchangeTrade, we could use your idea of having a sort of history manager and put it in place of the current arrayList of GrandExchangeTrade. This history manager would figure out how many things were bought/sold, what prices, etc. 

I like the idea of it being a field in the FlippingItem class because Its cleaner to have a single source of state/truth for items, which is already sort of the FlippingItem class. 

It would be a lot easier if we had access to better events (just give me the new quantity bought!), but I think your solution is great. What do you suggest we get started on working first? I'm going to write an outline for what I think the history manager should do/how it will look first, so that we are on the same page (I'm pretty sure we already are, but just so I know I didn't misinterpret anything).
