### ISSUE TITLE
Suggestion: Barrows Repair and similar

### ISSUE THREAD

**Issue by ogermain5** [Belieal/flipping-utilities#69]
I don't know if that is easy to do and/or part of the objectives of this tool.
Would it be possible to track barrows item bought broken and sold repaired? 
Similarly, there are items like zamorakian spear changed to hastae or battlestaves to mystic staves or items to set.

**Comment by Belieal** [comment]
While an interesting suggestion, this would require a lot of effort to create an accurate way of tracking. There are lots of scenarios we'd have to account for that could impact the tracking accuracy, not to mention the amount of items that would need to be applicable.

However, I think a more reasonable thing, that we could do as an update in the future, would be to show how much profit you could get from repairing and selling the items according to the margin checks you've done. (Perhaps add a checklist to list what items need to be margin checked before an accurate profit margin can be shown for that item)

Anyway, under any circumstance this would be a pretty big task that I'd argue a lot of other tools also provide a decent way of tracking (GE Tracker and the Wiki), so I wouldn't expect to see this until more pressing features are finalized.

Thank you so much for the suggestion, though! :)

**Comment by MauriceBenink** [comment]
I was actaully thinking about this a while ago.
And i am wondering. Wouldnt it be possible to instead do something along the lines of adding a special tab for this ?
And instead of it tracking it automatically you could manually configuring it.

example :
item convertion:
     input item      x-amount
     [ input item      x-amount
       ... ]

     output item   x-amount
     [ output item   x-amount
       ... ] 

     convertion gp cost : x


I think by letting people manually configuring something like this and allowing to configure which GE slot will be dedicated to this item convertion and simply assuming if any buy/sell offer in this slot (that matches the convertion items) will always be for this convertion
And once a couple of convertions are done and the config of the convertion gets changed then all completed offers of the convertion will simply persist (without change)

( + possibly allowing to configure x - amount already bough / x - amount already sold and taking those away from flips and adding the to the item convertion, But i dont know the code so i dont know how doable something like this would be)
