### ISSUE TITLE
save settings

### ISSUE THREAD

**Issue by stoddy15** [Belieal/flipping-utilities#71]
Hello

how can I save my settings so every time I load up runelite the timespan is: session instead of all

can you make it so it uses the last used settings?

also Belieal what's the point of hourly profit? I don't think you can replicate it every hour as the ge limit is every 4 hours. its a very unrealistic statistic so I don't think it should be used as its very misleading and not true

**Comment by zumaad** [comment]
Hey!

So, we are supposed to be saving the settings so that it remembers the timespan, but I just noticed a problem with it which is why it's not working...that will be fixed in the v1.3.1 which is coming soon.

The hourly profit shows up only in the "session" time span. The session starts when you first open the client. So, if you leave the client open and you aren't flipping, your profit can be deflated as it still counts as time passed. In that sense it isn't accurate. Perhaps we will revisit that statistic, thanks for bringing it up!

**Comment by zumaad** [comment]
Fixed in https://github.com/Belieal/flipping-utilities/pull/70/commits/aea877a2a22a7371b12815552da6561b2fd4ef72

**Comment by stoddy15** [comment]
@zumaad thank you. this plugin is honestly the best thing to happen for runelite! will you be coding it for the new hd client that may come out in the future? 

also please can you add a timer here
![68747470733a2f2f692e696d6775722e636f6d2f586154694b635a2e706e67](https://user-images.githubusercontent.com/63739578/82673181-59b00c00-9c39-11ea-91c7-d943c8675711.png)

**Comment by Belieal** [comment]
Unfortunately, I don't believe there's space for the timer on the panel without adding a third line to the item's title panel. If we were to add it on name line, there wouldn't be enough space for the names of some items.

Also, by the way, we're adding a reset button to the session timer in v1.3.1. You'll be able to simply right-click the timer and it will reset along with the profit/hr stat. :)
