### ISSUE TITLE
1.3.2 is added to master, but no update in the readme Changelog.

### ISSUE THREAD

**Issue by BramManuel** [Belieal/flipping-utilities#85]
Would love to see the readme up to date with the recent changes. 

For now I can look at the commit's but this is not confinent.

**Comment by Belieal** [comment]
The readme will be updated once RuneLite has reviewed and approved v1.3.2 (Whenever [this](https://github.com/runelite/plugin-hub/pull/366) gets merged on the plugin hub).

I'm waiting until it's available to users before I update it, since I've gotten a few people confused in the past about how to update their plugins before it was merged by RuneLite.
