### ISSUE TITLE
Wrong format for platinumtokens.com

### ISSUE THREAD

**Issue by vikke1234** [Belieal/flipping-utilities#91]
blighted super restore(4) is being formatted wrong, it should be formatted to `https://platinumtokens.com/item/blighted-super-restore-4` but is being formatted to `https://platinumtokens.com/item/blighted-super-restore4` note the lack of `-` before the 4.

**Comment by Belieal** [comment]
Thanks for the report. :)

It seems to be due to how we are scanning parentheses for suffixes. Suffixes require a different way of forming the URL due to how PT slugs the item names. Since one of the suffixes we look out for is `light`, the word `blighted` also tests true due to our greedy `itemName.contains(suffixString)` clause.

I've been able to fix this by only checking the string inside the parentheses instead of the whole item name.
